### PR TITLE
Fix editing task properties in details view

### LINKED ISSUE #403: [regression] edits don't get saved when focus is lost
With the change to Vue.js I noticed that whenever I make changes in dates or in descriptions I have to hit enter or click on 'save' in order for the change to be commited.

It used to be that you could just focus away and the changes got automatically commited. I don't know if this would be possible with the new framework, but if it is it would be nice to improve UX.

again, great job!

---

edit: this only happens when you click in the main area, which causes the right panel to collapse. Sorry about the confusion.

### PR DESCRIPTION
**Pull request by raimund-schluessler**
Fixes #403 and #404

@nachoparker Please have a look if this fixes the issues.

### CODE REVIEW

**Comment by nachoparker** [comment]
@raimund-schluessler thanks for your hard work. I built this branch and replaced `js/tasks.js` in a new instance and I did not see a difference.

Also please see my description of #403 again, as it was inaccurate.

**Comment by raimund-schluessler** [comment]
@nachoparker Are you sure tasks.js is not cached anywhere? Because I fixed exactly this. When you click in the main area, the edit should be saved now.

**Comment by raimund-schluessler** [comment]
The three cases in which possible changes are now additionally saved are:

- closing the details view
- navigating to a different task
- editing a different task property

**Comment by nachoparker** [comment]
I built your branch doing `make`, then copied `js/tasks.js` to a fresh docker container with a fresh NCP instance. I opened it in a new fresh private instance of firefox created for this purpose, so no cache.

It doesn't work for me. I do see in the console

```
Unhandled promise rejection TypeError: "right-hand side of 'in' should be an object, got null"
    St VueJS
    setSummary tasks.js:778
    h ical.js:402
    commit tasks.js:13
    commit tasks.js:13
    _withCommit tasks.js:13
    commit tasks.js:13
    commit ical.js:68
    t tasks.js:778
    _ tasks.js:13
    _invoke tasks.js:13
    e tasks.js:13
    cr tasks.js:778
    a tasks.js:778
    ur tasks.js:778
    O tasks.js:247
    ur tasks.js:778
    setSummary tasks.js:778
    h ical.js:412
    dispatch tasks.js:13
    dispatch ical.js:65
    r tasks.js:13
    setProperty tasks.js:778
    finishEditing tasks.js:778
    beforeDestroy tasks.js:778
    VueJS 18
```

**Comment by raimund-schluessler** [comment]
@nachoparker Thanks for testing, I can indeed reproduce this. Apparently I didn't test what happens when you click in the body and the details view is closed. I will check and let you know for further testing.

**Comment by raimund-schluessler** [comment]
@nachoparker Please have a look again, I fixed the issue (I hope 😉).

**Comment by raimund-schluessler** [comment]
@nachoparker Ping.

**Comment by nachoparker** [comment]
awesome! I'll be out for a couple days, will check this over the weekend.

**Comment by nachoparker** [comment]
Perfect, it works very well now both editing the text and the dates.

Thanks for your hard work!

**Pull request merged**
