### PR TITLE
Implement sharing calendars / task lists

### LINKED ISSUE #14: [Feature Request] Share task lists
Hi, 

will there be any futhur plan to add a share function, to share task lists with other users?

### PR DESCRIPTION
**Pull request by raimund-schluessler**
Implements a sharing menu in the calendar list. You can now share task lists with other users. Closes #14.

@skjnldsv I shamelessly copied most of the code from the Contacts app 😇 Works very good as far as I can tell.

Reviews very welcome!

### CODE REVIEW

**Comment by raimund-schluessler** [comment]
I will merge this now, so that the translations are getting updated. Reviews and testing is still welcome. If issues are found, we can fix them in later PRs.

**Comment by marbetschar** [comment]
@raimund-schluessler not quite sure where to put this, so I shamelessly add it to your pull request here :)

Is it possible to share a public link for a task list? I've seen it's possible in the calendar UI, not sure if I'm missing something in the tasks app. The use case is: I'd love to invite some Non-Nextcloud users to a given task list where they at least can see what's on it using their favourite task-app (Apple Reminders, Web UI, or whatever...)

**Comment by raimund-schluessler** [comment]
@marbetschar No, this is not possible yet. I think this issue is tracked in #469. As a workaround you could maybe create a calendar in the Calendar app and publicly share the WebCal link from the Calendar app. Tasks should also show up the in their favourite task-app then (but I haven't tested this).

**Comment by marbetschar** [comment]
@raimund-schluessler understood. Thanks for clarification!

**Pull request merged**
