### PR TITLE
Repeating tasks

### PR DESCRIPTION
**Pull request by sunkup**

### CODE REVIEW

**Comment by raimund-schluessler** [comment]
@jancborchardt Could you please invite @sunkup to nextcloud/tasks, so he can push his branch here?

**Comment by jancborchardt** [comment]
@sunkup invited you to the Nextcloud org and the Tasks team here on Github. I can also give you a guest account on our Nextcloud instance where we have various community channels. Let me know and I can add you with the email address used in your commits. :)

Also, are you coming to the Nextcloud Conference this September again? https://nextcloud.com/conference-2023/

**Comment by sunkup** [comment]
Great, thanks. Yes, you can add me to your nc instance please ~

And yes! All of us at bitfire plan to go :)

**Comment by raimund-schluessler** [comment]
@sunkup Could you push your changes to the nextcloud/tasks repo, please? Then it's easier to collaborate.

**Comment by sunkup** [comment]
> @sunkup Could you push your changes to the nextcloud/tasks repo, please? Then it's easier to collaborate.

It's all here already. There is not more than [9b27260](https://github.com/nextcloud/tasks/pull/2317/commits/9b272609722efeed6e4ad145ad8c7cedbcfffcdf) and [0acd5ae](https://github.com/nextcloud/tasks/pull/2317/commits/0acd5aee15f1839787b472c07311c28f57ae1cda).

I did not save/commit my experimental work - where I reused the calendar code for the sidebar UI - as it became to messy and I wanted to start over using rrule.js.

**Comment by raimund-schluessler** [comment]
> > @sunkup Could you push your changes to the nextcloud/tasks repo, please? Then it's easier to collaborate.
> 
> It's all here already. There is not more than [9b27260](https://github.com/nextcloud/tasks/pull/2317/commits/9b272609722efeed6e4ad145ad8c7cedbcfffcdf) and [0acd5ae](https://github.com/nextcloud/tasks/pull/2317/commits/0acd5aee15f1839787b472c07311c28f57ae1cda).
> 
> I did not save/commit my experimental work - where I reused the calendar code for the sidebar UI - as it became to messy and I wanted to start over using rrule.js.

Yes, I know, that's fine. I just meant that you create a branch in the tasks repository, and not in your private repo. This make checking out the PR and collaborating easier.

**Comment by raimund-schluessler** [comment]
New PR in #2318.

**Pull request closed without merging**
