### PR TITLE
Improve design of sidebar header

### PR DESCRIPTION
**Pull request by szaimen**
| Before | After |
|---|---|
| image | image |
| image | image |

Signed-off-by: szaimen <szaimen@e.mail.de>

### CODE REVIEW

**Comment by raimund-schluessler** [comment]
Besides that I am not sure that it really looks better, this needs to be done in the nextcloud/vue repository. I don't really want to deviate from the standard design, since it was the whole point of using the appsidebar component to unify the appearance over the different apps.

@nextcloud/designers anyway to get opinions whether we should change it in the components.

**Comment by st3iny** [comment]
Already fixed upstream in https://github.com/nextcloud/nextcloud-vue/pull/2054

**Comment by szaimen** [comment]
Thanks :)

**Pull request closed without merging**
