### PR TITLE
Allow to delete completed tasks, closes #69

### LINKED ISSUE #69: [Feature Request] Bulk deletion of completed tasks.
### Steps to reproduce
1. Click "Load remaining completed tasks." button.
2.
3.

### Expected behaviour
Button or some other control/logic to allow bulk deletion of completed tasks.

### Actual behaviour
No button or some other control/logic to allow bulk deletion of completed tasks.

### Server configuration
**Operating system**:
Debian Jesse
**Web server:**
Lighttpd/1.4.35
**Database:**
MySql
**PHP version:**
5.5
**Nextcloud version:** (see Nextcloud admin page)
11.0.2
**Tasks version:** (see Nextcloud apps page)
0.9.5
**Updated from an older Nextcloud or fresh install:**
Fresh
**Signing status:**
No errors have been found.
```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```

**List of activated apps:**
Enabled:
  - activity: 2.4.1
  - calendar: 1.5.2
  - comments: 1.1.0
  - contacts: 1.5.3
  - dav: 1.1.1
  - federatedfilesharing: 1.1.1
  - federation: 1.1.1
  - files: 1.6.1
  - files_pdfviewer: 1.0.1
  - files_sharing: 1.1.1
  - files_texteditor: 2.2
  - files_trashbin: 1.1.0
  - files_versions: 1.4.0
  - files_videoplayer: 1.0.0
  - firstrunwizard: 2.0
  - gallery: 16.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - nextcloud_announcements: 1.0
  - notifications: 1.0.1
  - password_policy: 1.1.0
  - provisioning_api: 1.1.0
  - rainloop: 4.28.1
  - serverinfo: 1.1.1
  - sharebymail: 1.0.1
  - survey_client: 0.1.5
  - systemtags: 1.1.3
  - tasks: 0.9.5
  - theming: 1.1.1
  - twofactor_backupcodes: 1.0.0
  - updatenotification: 1.1.1
  - workflowengine: 1.1.1
Disabled:
  - admin_audit
  - encryption
  - external
  - files_accesscontrol
  - files_automatedtagging
  - files_external
  - files_retention
  - templateeditor
  - user_external
  - user_ldap
  - user_saml
```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```

### PR DESCRIPTION
**Pull request by raimund-schluessler**

### CODE REVIEW

**Comment by raimund-schluessler** [comment]
@skjnldsv How do I use the Modal component from the vue-components?

When trying to open the modal by setting `modalOpen` to `true` in https://github.com/nextcloud/tasks/pull/414/files#diff-754de562f4fc8d7b98f49629450e0efcR27 I get
```
[Vue warn]: Failed to mount component: template or render function not defined.

found in

---> <Modal>
       <DeleteCompletedModal> at src/components/DeleteCompletedModal.vue
         <Calendar> at src/components/TheCollections/Calendar.vue
           <App> at src/app.vue
             <Root> vue.runtime.esm.js:619
```

**Comment by raimund-schluessler** [comment]
> 
> 
> @skjnldsv How do I use the Modal component from the vue-components?
> 
> When trying to open the modal by setting `modalOpen` to `true` in https://github.com/nextcloud/tasks/pull/414/files#diff-754de562f4fc8d7b98f49629450e0efcR27 I get
> 
> ```
> [Vue warn]: Failed to mount component: template or render function not defined.
> 
> found in
> 
> ---> <Modal>
>        <DeleteCompletedModal> at src/components/DeleteCompletedModal.vue
>          <Calendar> at src/components/TheCollections/Calendar.vue
>            <App> at src/app.vue
>              <Root> vue.runtime.esm.js:619
> ```

Solved it, had to import it like this
```
import { Modal } from 'nextcloud-vue'
```
instead of this
```
import Modal from 'nextcloud-vue'
```
🤦‍♂

**Comment by skjnldsv** [comment]
AHaha! Glad it's fixed!
We use it in contacts if you want ;)

**Comment by raimund-schluessler** [comment]
This implements a modal which allow to delete all completed tasks in a calendar. The workflow is
1. Click on "Load all completed tasks."
Screenshot_2019-05-20 Aufgaben - Nextcloud(3)

2. Click on "Delete all completed tasks." button to open the modal
Screenshot_2019-05-20 Aufgaben - Nextcloud(4)

3. Click on "Delete completed tasks." button
Screenshot_2019-05-20 Aufgaben - Nextcloud(2)

**Pull request merged**
