### PR TITLE
Disable autocomplete for new task "target" field

### LINKED ISSUE #1397: Disable autocomplete for new task "target" field
### Steps to reproduce
1. Open the tasks app
2. Click into the new task "target" input field above the task list to add a new task

### Expected behaviour
The user can instantly enter the name of the new task without being distracted

### Actual behaviour
The browser shows a popup with (in my case) 6 recently added tasks (browser autocomplete feature). This distracts the user as the eyes tend to first look to the tasks he just added (most likely he does not want to add them again).

image

I would like to disable the autocomplete feature.

### Server configuration
**Operating system**: Debian 10

**Web server:** Nginx

**Database:** MariaDB

**PHP version:** 7.4

**Nextcloud version:** 20.0.5

**Tasks version:** 0.13.6

**Updated from an older Nextcloud or fresh install:** Updated

**Signing status:**

No errors have been found.

**Are you using external storage, if yes which one:** No

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** No

### Client configuration
**Browser:** Brave 1.18.78 (Chromium: 87.0.4280.141)

**Operating system:** Ubuntu 20.10

I've seen the code for the input field rendered by the browser is the following:
```html
<form name="addTaskForm">
<input id="target" placeholder="Eine Aufgabe zu &quot;Aufgaben&quot; hinzufügen…" class="transparent reactive">
</form>
```
I would recommend adding `autocomplete="off"` to the input field. If you like, I can provide a PR for that.

### PR DESCRIPTION
**Pull request by cnmicha**
Close #1397

### CODE REVIEW

**Comment by cnmicha** [comment]
@raimund-schluessler Done :)

**Comment by cnmicha** [comment]
@raimund-schluessler Is there a timeline for releasing a new version including this fix? The current one is from Nov 2020.

**Comment by raimund-schluessler** [comment]
@cnmicha I haven't had much time to work on the app for a while and only recently picked it up again. You can see here https://github.com/nextcloud/tasks/milestone/8 what is still on the list for the next release. So it will likely take another couple of weeks. If you want, I can pack the current master branch into a release for you, so you could even help testing 🙂

**Comment by cnmicha** [comment]
@raimund-schluessler Alright, glad to hear. No need to create a separate release for me, maybe I'll have time to look into the milestone issues. 😃

**Pull request merged**
