### PR TITLE
Fix app-sidebar, closes #58, closes #35

### LINKED ISSUE #35: Do not overwrite #app-sidebar properties
This might mess up theming.

### LINKED ISSUE #58: UI is messed up
### Steps to reproduce
unfortunately i'm not sure right now _(please be patient, these are my first steps on github!)_

### Expected behaviour
a clean an functional UI

### Actual behaviour
have a look at the screenshot... aufgaben - testcloud - 2017-03-01
 the UI is definitely not like it should be.

### Server configuration
i'm using a hoster, so i can't tell you everything exactly...

**Operating system**: Linux 3.13.0-110-generic #157-Ubuntu SMP x86_64

**Web server:** Apache 2.0

**Database:** mysql 5.6.33

**PHP version:** 7.0.14

**Nextcloud version:** 11.0.2.7

**Tasks version:** 0.9.4

**Updated from an older Nextcloud or fresh install:** updated from 11.0.1.2 with the app

**Signing status:**

```
Integrity checker has been disabled. Integrity cannot be verified.
```
i think this is because i tried to "sideload" the checksum-app via FTP because it can't be downloaded via the apps-menu _(Client error response [url] https://herzberg-digital.de/checksum.tar.gz [status code] 404 [reason phrase] Not Found)_... then it showed an app-update immediately and after applying that i got an integrity-warning on the admin-page.

**List of activated apps:**
i use this as a testing-instance so it is sadly a huge list. - at least i'm pretty sure the problems in the main-window are related with JavaScript XMPP Chat.
```
Activity 2.4.1
Collaborative tags 1.1.3
Comments 1.1.0
Default encryption module 1.4.1
Deleted files 1.1.0
External storage support 1.1.2
External user support 0.4
Federation 1.1.1
File access control 1.1.2
File sharing 1.1.1
First run wizard 2.0
Gallery 16.0.0
Log Reader 2.0.0
Mail template editor 0.2
Nextcloud announcements 1.0
Notifications 1.0.1
Password policy 1.1.0
PDF viewer 1.0.1
Retention 1.0.1
Server info 1.1.1
Share by mail 1.0.1
Text editor 2.2
Theming 1.1.1
Update notification 1.1.1
Usage survey 0.1.5
Versions 1.4.0
Video player 1.0.0
Activities for shared file downloads 1.0.0
Activity Log 0.0.1
Admin notifications 1.0.0
Announcement Center 3.0.0
AppOrder 0.3.3
Calendar 1.5.0
Contacts 1.5.3
JavaScript XMPP Chat 3.1.1
Keeweb 0.3.0
Mail 0.6.2
News 10.1.0
Notizen 2.2.0
Phone Sync 1.11.5
RainLoop 4.26.1
Reader (ebook reader) 0.8.4
Tasks 0.9.4
Video calls 1.2.0
```

**The content of config/config.php:**

```
<?php
$CONFIG = array (
  'instanceid' => 'XXX',
  'passwordsalt' => 'XXX',
  'secret' => 'XXX',
  'trusted_domains' => 
  array (
    0 => 'test.domain.tld',
  ),
  'datadirectory' => '/www/htdocs/XXX/test/nextcloud/data',
  'overwrite.cli.url' => 'http://test.domain.tld/nextcloud',
  'dbtype' => 'mysql',
  'version' => '11.0.2.7',
  'dbname' => 'XXX',
  'dbhost' => 'localhost',
  'dbport' => '',
  'dbtableprefix' => 'XXX_',
  'dbuser' => 'XXX',
  'dbpassword' => 'XXX',
  'logtimezone' => 'Europe/Berlin',
  'installed' => true,
  'default_language' => 'de',
  'memcache.local' => '\\OC\\Memcache\\ArrayCache',
  'tempdirectory' => '/www/htdocs/XXX/test/nextcloud/tmp/',
  'updater.release.channel' => 'production',
  'loglevel' => 0,
  'theme' => '',
  'updater.secret' => 'XXX',
  'maintenance' => false,
);
```

**Are you using external storage, if yes which one:** no

**Are you using encryption:** yes, just in case for external storage.

**Are you using an external user-backend, if yes which one:** no

#### Browser
i'm using Firefox 51.0.1 (64-Bit)

### PR DESCRIPTION
**Pull request by raimund-schluessler**
This fixes the issue that the app-sidebar does not work properly when other apps overwrite some css properties.

Please have a look @DJCrashdummy

### CODE REVIEW

**Comment by raimund-schluessler** [comment]
The sidebar can now be toggled correctly and does not hide the content.

bildschirmfoto am 2017-03-01 um 22 02 02

When the chat sidebar is open then the sidebar is blocking the content partially
bildschirmfoto am 2017-03-01 um 22 02 11

However, this is due to the way ojsxc changes the layout and also happens to e.g. the files app.
bildschirmfoto am 2017-03-01 um 22 02 18

There should be a bug report for the ojsxc app.

**Comment by raimund-schluessler** [comment]
Merging this as the reporter of the issue approved.

**Comment by DJCrashdummy** [comment]
@raimund-schluessler: as you mentioned in your post https://github.com/nextcloud/tasks/pull/59#issuecomment-283470081, is there a bug report at ojsxc or have you opened one?

i didn't find one and would have opened one on my own, but i'm not able to provide more information than in your post (or even just link it) and i'm not really sure where it would suit best:
- https://github.com/jsxc/jsxc
- https://github.com/nextcloud/jsxc.nextcloud
- https://github.com/owncloud/jsxc.chat

since i'm new to github and all the stuff i would appreciate at least some guidance how to go further.

**Comment by raimund-schluessler** [comment]
I haven't reported a bug yet, mostly because I also wasn't sure where to post it. Also I didn't notice that there is a NC/JSXC repo https://github.com/nextcloud/jsxc.nextcloud, which is probably the best option.

I guess it would be sufficient to report how to reproduce the bug, you can also include my screenshots if you want.

**Comment by sualko** [comment]
No, it's not that easy, but I packed you a nightly: [ojsxc-3.2.0-fixlayout.0308.tar.gz](https://github.com/nextcloud/tasks/files/828065/ojsxc-3.2.0-fixlayout.0308.tar.gz)

**Pull request merged**
