### PR TITLE
[WIP] Manual sorting

### LINKED ISSUE #86: [User Question] Make Tasks show up in calendar.
Hello,
as the title says:
Is it possible to make the tasks show up in the calendar app/widget? So I can see what tasks are coming?

### PR DESCRIPTION
**Pull request by raimund-schluessler**
This PR aims to implement the possibility to manualls sort the task list by drag-and-drop and will fix #86.

TODOs:
- [x] Enable manually sorting tasks in the list view
- [ ] Fix sorting of tasks when list is ordered in reverse
- [ ] Enable sorting tasks in collection views
- [ ] Enable sorting of subtasks
- [ ] Automatically switch to manual sorting if a task is dragged

Continues from https://github.com/owncloud/tasks/pull/358

### CODE REVIEW

**Comment by charlag** [comment]
Is this going to be developed or it will be part of #194 ?

**Comment by raimund-schluessler** [comment]
> Is this going to be developed or it will be part of #194 ?

#194 Is meant to port the app to Vue.js providing the same features as before. It will not have major new features, only small things which have to be reimplemented anyway will be changed/improved. New features will be implemented after #194 is done.

**Comment by raimund-schluessler** [comment]
Closing as it needs to be adjusted to the Vue rewrite first.

**Comment by waynema02** [comment]
As #194 has been closed, would this PR be reopened and worked on? Manual sorting really helps to organize the tasks in flexible manner. Thanks!

**Comment by dohlin** [comment]
Any update on whether this can be re-opened and reviewed?  This is a much needed feature imho

**Comment by raimund-schluessler** [comment]
The current PR is https://github.com/nextcloud/tasks/pull/237. But there is nothing to review yet, needs to be developed.

**Pull request closed without merging**
