### PR TITLE
Fix escaping of placeholder strings

### LINKED ISSUE #1123: Special characters show html-escaped in "Add task" input field placeholder value
### Steps to reproduce
1. Add a new list with the name "Test < and &"
2. Open the list

### Expected behaviour
The placeholder text in the add new tasks input field is:

> Add task to "Test < and &"...

### Actual behaviour
The placeholder text in the add new tasks input field is:

> Add task to "Test &lt; and &amp;"...

## Server configuration detail

**Operating system:** Linux 4.15.0-101-generic #102-Ubuntu SMP Mon May 11 10:07:26 UTC 2020 x86_64

**Webserver:** nginx/1.14.0 (fpm-fcgi)

**Database:** mysql 5.7.30

**PHP version:** 

7.2.24-0ubuntu0.18.04.6
Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, sodium, session, standard, cgi-fcgi, apcu, mysqlnd, PDO, xml, apc, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, iconv, imagick, intl, json, exif, mysqli, pdo_mysql, Phar, posix, readline, shmop, SimpleXML, sockets, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xmlreader, xmlwriter, xsl, zip, Zend OPcache

**Nextcloud version:** 18.0.6 - 18.0.6.0

**Updated from an older Nextcloud/ownCloud or fresh install:** 

**Where did you install Nextcloud from:** unknown

<details><summary>Signing status</summary>

Array
(
)

</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - accessibility: 1.4.0
 - activity: 2.11.0
 - apporder: 0.10.0
 - bruteforcesettings: 1.6.0
 - calendar: 2.0.3
 - cloud_federation_api: 1.1.0
 - comments: 1.8.0
 - contacts: 3.3.0
 - dav: 1.14.0
 - federatedfilesharing: 1.8.0
 - federation: 1.8.0
 - files: 1.13.1
 - files_pdfviewer: 1.7.0
 - files_rightclick: 0.15.2
 - files_sharing: 1.10.1
 - files_trashbin: 1.8.0
 - files_versions: 1.11.0
 - files_videoplayer: 1.7.0
 - firstrunwizard: 2.7.0
 - issuetemplate: 0.6.0
 - logreader: 2.3.0
 - lookup_server_connector: 1.6.0
 - mail: 1.4.1
 - maps: 0.1.6
 - nextcloud_announcements: 1.7.0
 - notes: 3.6.0
 - notifications: 2.6.0
 - oauth2: 1.6.0
 - onlyoffice: 4.3.0
 - password_policy: 1.8.0
 - phonetrack: 0.6.4
 - photos: 1.0.0
 - privacy: 1.2.0
 - provisioning_api: 1.8.0
 - recommendations: 0.6.0
 - serverinfo: 1.8.0
 - settings: 1.0.0
 - sharebymail: 1.8.0
 - spreed: 8.0.9
 - support: 1.1.1
 - survey_client: 1.6.0
 - systemtags: 1.8.0
 - tasks: 0.13.2
 - text: 2.0.0
 - theming: 1.9.0
 - twofactor_backupcodes: 1.7.0
 - updatenotification: 1.8.0
 - viewer: 1.2.0
 - workflowengine: 2.0.0
Disabled:
 - admin_audit
 - encryption
 - files_external
 - user_ldap

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "cloud.vedantawiki.org"
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "dbtype": "mysql",
    "version": "18.0.6.0",
    "overwrite.cli.url": "https:\/\/cloud.vedantawiki.org",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbport": "",
    "dbtableprefix": "oc_",
    "mysql.utf8mb4": true,
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "memcache.local": "\\OC\\Memcache\\APCu",
    "maintenance": false,
    "theme": "",
    "loglevel": 2,
    "updater.secret": "***REMOVED SENSITIVE VALUE***"
}
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** 

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

## Client configuration

**Browser:** Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:78.0) Gecko/20100101 Firefox/78.0

**Operating system:** 

## Logs

<details><summary>Web server error log</summary>

```
Insert your web server log here 
```
</details>

<details><summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

<details><summary>Browser log</summary>

Insert your browser log here, this could for example include:

	a) The javascript console log
	b) The network log
	c) ...
</details>

### PR DESCRIPTION
**Pull request by raimund-schluessler**
Fixes #1123. Related to https://github.com/nextcloud/server/pull/20976.

This will only work with Nextcloud 18.0.5 https://github.com/nextcloud/server/pull/21127 and 19.0.1 https://github.com/nextcloud/server/pull/21126 onwards.

Before merging we need to check that this doesn't introduce any XSS vulnerabilities.

### CODE REVIEW

**Comment by raimund-schluessler** [comment]
Seems to be fine XSS wise, but another opinion from @nextcloud/javascript and @ChristophWurst (since you introduced the fix in server) would be great.

**Comment by raimund-schluessler** [comment]
> Make not to use `v-html` with this

Thanks for the feedback. We don't use `v-html` anywhere in Tasks (I also think one should use a component with a render function instead of `v-html`, but that's a different story I guess.)

**Comment by raimund-schluessler** [comment]
I just realized there are more occurrences where we have to fix it:
- Creating a calendar with an already used name
- Deleting a calendar
- Removing a calendar share
- Batch-deleting tasks from a calendar

**Comment by raimund-schluessler** [comment]
I think I found all occurrences now.

**Comment by gitaarik** [comment]
Just a question, what is `this.$t`? It looks like vue-i18n but I don't recognize all the options. Also I'm not very familiar with Vue so I don't know where to look to find out where `this.$t` is defined.

**Comment by gary-kim** [comment]
It's Nextcloud's l10n system. You will find it bound to `window.t` on all Nextcloud pages or you can use [this](https://github.com/nextcloud/nextcloud-l10n) npm package. You find where it gets set here:

https://github.com/nextcloud/tasks/blob/e56ed81a2f6b91ec6abc37039619bc8da0741882/src/main.js#L61-L66

**Comment by gitaarik** [comment]
Aha I see, cool. So the translations of nextcloud apps are all managed 
by a centralized system? Also, don't you mean it's bound to the `Vue` 
object instead of the `window` object?

**Comment by raimund-schluessler** [comment]
> So the translations of nextcloud apps are all managed by a centralized system?

Yes, they are handled by Transifex. The translateable strings get extracted from the source automatically, get uploaded to transifex, translated there, and the translated strings are pushed to the repo by @nextcloud-bot.

> Also, don't you mean it's bound to the `Vue` object instead of the `window` object?

Both, actually. We bind the `window.t` to the Vue object here:
https://github.com/nextcloud/tasks/blob/e56ed81a2f6b91ec6abc37039619bc8da0741882/src/main.js#L62

**Comment by gitaarik** [comment]
Aha cool, so Nextcloud does not enforce apps to be written in Vue?

Sorry if I'm bothering you with these questions. I really like the 
Nextcloud project and especially the tasks app at the moment. I'm using 
it in combination with the android app https://tasks.org/. That app also 
supports sub-tasks and synchronizes nicely with Nextcloud. I am sharing 
a task list with my partner now and it's really handy. I would like to 
get a notification when my partner adds new items in the list. So 
therefore the creator/owner of the task should be saved with the item so 
it can be synchronized to this app so the app can get a feature to send 
a notification when new items from another person have been synchronized.

**Comment by raimund-schluessler** [comment]
> Aha cool, so Nextcloud does not enforce apps to be written in Vue?

You can write your apps using React or Angluar or plain JavaScript as well. However, I would highly recommend Vue, since the Nextcloud interface library https://github.com/nextcloud/nextcloud-vue is written in Vue and Vue is the standard framework used all over Nextcloud. 

Let's discuss the other questions in the respective issue.

**Pull request merged**
