### PR TITLE
Implement manual sorting

### LINKED ISSUE #28: [Feature Request] Sort tasks
### Steps to reproduce
1. Create a list
2. Add tasks
3. Try to sort task using drag and drop

### Expected behavior
I would like to be able to sort tasks, now I can only star them and this is quite limited

### Actual behavior
Now I only can star them, and they are alphabetically sorted.

### Server configuration
**Nextcloud version:** (see Nextcloud admin page)
11
**Tasks version:** (see Nextcloud apps page)
0.9.4
**Updated from an older Nextcloud or fresh install:**
Updated since owncloud 7

### PR DESCRIPTION
**Pull request by raimund-schluessler**
This PR implements manual sorting of tasks.
In order to manually sort a task list, select `Manually` in the sort-order dropdown and drag the tasks to the position you want them at. The sort-order syncs to Reminders on iOS (and probably MacOS, but I can not test this).

manual-order

Please test this feature with this build of the Tasks app containing manual sorting:
[tasks.tar.gz](https://github.com/nextcloud/tasks/files/4601649/tasks.tar.gz)

Closes #28.

### CODE REVIEW

**Comment by nachoparker** [comment]
Is this for calendars? One change that lowers my UX after the port to Vue (great otherwise) is that my main calendar is now at the bottom. It would be nice to be able to drag it to the top on the left sidebar so that we can have our main task-calendar at the top, readily accessible when we open the app.

Thanks!

**Comment by raimund-schluessler** [comment]
No, this will be for tasks. For sorting calendars, there is a separate issue already #15. Calendars are now sorted alphabetically to have a consistent order. So as a workaround to have your default calendar at the top you could adjust its name accordingly.

**Comment by aiomaster** [comment]
Hi,
thanks for the work. I would like to know what is the current state of this. Is there something missing to get basic manual sorting in tasks?
Thanks!

**Comment by raimund-schluessler** [comment]
> I would like to know what is the current state of this. Is there something missing to get basic manual sorting in tasks?

Only time to implement it is missing 😉

**Comment by zeroepix** [comment]
What order will you be doing the sorting in?

As I understand it, for outstanding tasks it was: due>priority>start>alphabetically

For those who might read along and not understand, it means if two tasks are due the same day, the priority will be used to order them. If due date and priority are the same, then start will show the order, etc.

With the manual sort, will it override priority and due dates? I'm thinking there will be some usability conflict and I'm curious as to your solution.

**Comment by raimund-schluessler** [comment]
> With the manual sort, will it override priority and due dates? I'm thinking there will be some usability conflict and I'm curious as to your solution.

There will be a new sort-order option "manual" in the dropdown menu. Only when this is selected, the manual sort order will be considered.

**Comment by HieronymusCH** [comment]
I second the manual sorting order.

And thank you for your work.
\o/

**Comment by kilrau** [comment]
Keep it up! @raimund-schluessler

**Comment by szaimen** [comment]
🎉

**Pull request merged**
