### PR TITLE
OpenTask-Support

### PR DESCRIPTION
**Pull request by newhinton**
I have opened a feature request regarding the OpenTasks-android-app, and i have started developing this feature. Since i have progressed quiet far, i wanted to open a pull request. There are still issues with my code, but i hope to get it fixed soon and or recieve help here.

[Feature Request](https://github.com/nextcloud/tasks/issues/159)

Current Issues: 
List elements are not updating their state after they were deleted (or checked). This only affects the UI, the changes are stored properly.

Adding Tasks is not the most elegant solution.

Hiding checklisttasks does not work, maybe this is related to the first issue.

If i have missed requirements for this pull request, please tell me what is missing, i try to get it fixed then.  Any help is appreciated.

### CODE REVIEW

**Comment by newhinton** [comment]
I have not yet been in touch with the developers from OpenTasks, which leads to a "problem":
Currently, the code looks for <tag></tag> and parses everything in between, but the OpenTasks-app does not use tags. I will need to change this behaviour according to the OT-Devs later.

**Comment by raimund-schluessler** [comment]
Thanks for the contribution. I haven't really had time to check it yet, but one thing I noticed is that you are translating and changing the files in https://github.com/nextcloud/tasks/tree/master/l10n. This is not necessary or possible. Translations are handled automatically via Transifex, so don't change anything in l10n. Just add the strings in the appropriate functions and the bot will push it to Transifex.

Also, could you add a screenshot please 😃

**Comment by newhinton** [comment]
Sure thing!

<a href="https://www.imagebanana.com/s/1031/PJhkX24g.html" target="_blank"></a>

**Comment by newhinton** [comment]
And for Subtasks:

<a href="https://www.imagebanana.com/s/1031/WiUzdQaz.html" target="_blank"></a>

**Comment by newhinton** [comment]
@raimund-schluessler i cant find out why the ui does not refresh after changes (checkboxes stay checked, deleted elements still show up) even if the proper actions are taken and stored. It only affects the new element, not the already existing ones. Maybe you have a clue where to investigate or even what the problem could be?

**Comment by raimund-schluessler** [comment]
Sorry, I am pretty busy atm, I try to have a look this weekend.

**Comment by raimund-schluessler** [comment]
I somehow screwed up to push to your repository, sorry for that. Your commits are in the newhinton branch now, the new PR is #177.

**Pull request closed without merging**
