### PR TITLE
Apply last all-day setting to newly created dates

### LINKED ISSUE #615: [Feature Request] Remember setting of all-day toggle for creation of new tasks
I would love to have the all day option set by default.

### PR DESCRIPTION
**Pull request by raimund-schluessler**
Closes #615

As discussed in https://github.com/nextcloud/tasks/pull/656#issuecomment-539482473 applying the all-day setting to newly created dates is still to be done here.

### CODE REVIEW

**Comment by jakobroehrl** [comment]
@raimund-schluessler 
Checked your changes. Saving the settings works. 
Is it possible to show allDay always and remove the connection to the dates?

**Comment by jakobroehrl** [comment]
@raimund-schluessler
Could we solve #637 easy if we copy and modify these change a litte bit?

**Comment by raimund-schluessler** [comment]
> 
> 
> @raimund-schluessler
> Could we solve #80 easy if we copy and modify these change a litte bit?

Well, we could store the last view in the same way.

**Comment by raimund-schluessler** [comment]
@jakobroehrl This should work as expected now. Can you please test?

**Comment by jakobroehrl** [comment]
@raimund-schluessler Thanks for your work. 
Unfortunately I don't see any changes. Added task 1, swiched to all day, added task 2, all day isn't set. 
Did I make a mistake?
Pulled fix-615, npm install, cleared the browser cache.

**Comment by raimund-schluessler** [comment]
> Pulled fix-615, npm install, cleared the browser cache.

`npm install` is not necessary, but you need to build the app with `make` or `make build-js`. If it is built correctly you should see requests for saving the setting to the server when changing the all-day setting.

**Comment by jakobroehrl** [comment]
Yes, I see the network request when I check/uncheck the all-day checkbox.

**Comment by raimund-schluessler** [comment]
> Yes, I see the network request when I check/uncheck the all-day checkbox.

So, does it work now? Did you build the app?

**Comment by jakobroehrl** [comment]
> So, does it work now? Did you build the app?
I build the app.
I see two request after I ticked all-day
But when I create a new task I have to tick all-day every time.

**Comment by raimund-schluessler** [comment]
Hm, I think I didn't check if it works when creating a new task (although I think it should). Could you check whether it remembers the setting when you remove start and due date and set it again. I will check in the evening if it works for creating new tasks.

**Comment by jakobroehrl** [comment]
> Hm, I think I didn't check if it works when creating a new task (although I think it should). Could you check whether it remembers the setting when you remove start and due date and set it again. I will check in the evening if it works for creating new tasks.

That's working. It would be great if it would work for new tasks, too. Thank you!

**Comment by raimund-schluessler** [comment]
> That's working. It would be great if it would work for new tasks, too. Thank you!

Weird. I will check.

**Comment by raimund-schluessler** [comment]
@jakobroehrl It works as it should for me. This is what I do:
- create a new task
- set a start or due date, make it all-day
- create a second task
- set a start or due date, which is already all-day

Could you please describe in detail what you do, so it doesn't work?

The only problem I noticed is that creating tasks in the "Today" collection does not respect the all-day setting yet. I will adjust this.

**Comment by raimund-schluessler** [comment]
Just to make it clear, when you create a task, all-day is only set when you set a start or due date. Without a date, all-day cannot be applied (since it is not a value itself, but determined from the present date).

**Comment by jakobroehrl** [comment]
Now it's working. :)
Restarted the VM und cleared the cache again.

**Pull request merged**
