### PR TITLE
first try to implement the nextcloud checkbox design

### PR DESCRIPTION
**Pull request by jakobroehrl**
Signed-off-by: Jakob <jakob.roehrl@web.de>

@raimund-schluessler: Cloud you help me here with the CSS?

### CODE REVIEW

**Comment by raimund-schluessler** [comment]
@jakobroehrl I haven't had time to check the functionality or the CSS yet, but I still have some feedback already:

- [ ] The ID of an element has to be unique on the whole page. You have to add a unique identifier to the ID if you use it in a reusable component. Just append `task.uid` to your ID. `:id="' toggleCompleted_' + task.uid" should work like here https://github.com/nextcloud/tasks/blob/master/src/components/TheList.vue#L52
- [ ] The checkbox has to be disabled in case the calendar is read-only: `task.calendar.readOnly`.
- [ ] The checkbox style is used for the toggle all day checkbox in the details view as well: https://github.com/nextcloud/tasks/blob/master/src/components/TheDetails.vue#L132-L137. It should be adjusted too.
- [ ] The aria attributes should be kept. Just add them to the input element.

Bonus:

- [ ] The checkmark icon is used as indicator to show a successful sync to the server. Once we have the final design, we should adjust the icon as well: https://github.com/nextcloud/tasks/blob/master/img/src/color/checkmark-color.svg

**Comment by jakobroehrl** [comment]
@raimund-schluessler 
Added your Feedback and the CSS from Julius: https://github.com/nextcloud/tasks/issues/506#issuecomment-526306976

**Comment by raimund-schluessler** [comment]
Should be all good now.

**Comment by raimund-schluessler** [comment]
Before:
Screenshot_2019-09-01 Aufgaben - Nextcloud(1)

After:
Screenshot_2019-09-01 Aufgaben - Nextcloud

**Pull request merged**
