### PR TITLE
Fix translate function for Chrome 77 Beta

### PR DESCRIPTION
**Pull request by raimund-schluessler**
This fixes an issue occuring in Chrome 77 Beta, see #566. Although this would fix the issue and not cause any other problems (as far as I know atm), I am a bit reluctant to actually merge this because:

- we fix an issue occuring in the Beta release of Chrome which might not occur anymore in the stable release
- in case the issue persists in the Chrome stable release, the translate function `t(...)` should actually be adjusted in Nextcloud server and not in the apps.

As a conclusion, I will for now not merge this fix but wait how things go with Chrome stable. In case it persists, we have a fix at hand and can react quickly. For everyone that wants/has to use Chrome Beta here is a version of the app containing the fix:
[tasks.zip](https://github.com/nextcloud/tasks/files/3595292/tasks.zip)

### CODE REVIEW

**Comment by mcocolla** [comment]
Chrome 77 just went stable release and in my testing the problem persists with the translate function. I've also noticed placeholder text on modal dialogs in 77, not sure if that is also part of the same root problem. 

Annotation 2019-09-10 144127

**Comment by raimund-schluessler** [comment]
> Chrome 77 just went stable release and in my testing the problem persists with the translate function. I've also noticed placeholder text on modal dialogs in 77, not sure if that is also part of the same root problem.

Indeed, I can confirm that Chrome 77 produces this error. Since there is no solution in server yet, let's merge this PR to fix the problem in the Tasks app. We can then still react to whatever changes will be introduced to server.

**Comment by raimund-schluessler** [comment]
@mcocolla Can you elaborate on this modal dialog error? How did you produce this modal?

**Comment by mcocolla** [comment]
@raimund-schluessler This dialog came from the settings > basic settings and clicking the store credentials button on the Email server settings.

**Pull request merged**
